# Base image
FROM python:3

# Set the working directory inside the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install the Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose the port your app will run on (change it if your app uses a different port)
EXPOSE 5000

# Command to run your application
CMD ["python", "app.py"]

